// Additional Chennai Temples Data
// This file contains a comprehensive list of temples in Chennai
// Coordinates are approximate - verify with Google Maps for accuracy

export const chennaiTemplesData = [
  {
    name: 'Kalikambal Temple',
    deity: 'Kalikambal (Kamakshi)',
    address: 'Thambu Chetty Street, Georgetown, Chennai, Tamil Nadu 600001',
    city: 'Chennai',
    locality: 'Georgetown',
    latitude: 13.0900,
    longitude: 80.2900,
  },
  {
    name: 'Sri Anjaneyar Temple',
    deity: 'Hanuman',
    address: 'Nanganallur, Chennai, Tamil Nadu 600061',
    city: 'Chennai',
    locality: 'Nanganallur',
    latitude: 12.9800,
    longitude: 80.2000,
  },
  {
    name: 'Sringeri Sharadamba Temple',
    deity: 'Sharadamba',
    address: 'Thyagaraya Nagar (T.Nagar), Chennai, Tamil Nadu 600017',
    city: 'Chennai',
    locality: 'T. Nagar',
    latitude: 13.0400,
    longitude: 80.2400,
  },
  {
    name: 'Sree Ayyappan-Guruvayurappan Temple',
    deity: 'Ayyappan, Guruvayurappan',
    address: 'Mahalingapuram, Nungambakkam, Chennai, Tamil Nadu 600034',
    city: 'Chennai',
    locality: 'Mahalingapuram',
    latitude: 13.0600,
    longitude: 80.2400,
  },
  {
    name: 'Vedapureeswarar Temple',
    deity: 'Shiva',
    address: 'Thiruverkadu, Chennai, Tamil Nadu 600077',
    city: 'Chennai',
    locality: 'Thiruverkadu',
    latitude: 13.1500,
    longitude: 80.1500,
  },
  {
    name: 'Arupadai Veedu Murugan Temple',
    deity: 'Murugan',
    address: 'Besant Nagar, Chennai, Tamil Nadu 600090',
    city: 'Chennai',
    locality: 'Besant Nagar',
    latitude: 12.9980,
    longitude: 80.2700,
  },
  {
    name: 'Sri Anantha Padmanabha Swamy Temple',
    deity: 'Vishnu',
    address: 'Adyar, Chennai, Tamil Nadu 600020',
    city: 'Chennai',
    locality: 'Adyar',
    latitude: 13.0100,
    longitude: 80.2600,
  },
  {
    name: 'Sri Ayyappan Temple',
    deity: 'Ayyappan',
    address: 'Raja Annamalaipuram, Chennai, Tamil Nadu 600028',
    city: 'Chennai',
    locality: 'Raja Annamalaipuram',
    latitude: 13.0200,
    longitude: 80.2700,
  },
  {
    name: 'Mathyakailash Temple',
    deity: 'Ganesha',
    address: 'Sardar Patel Road, Adyar, Chennai, Tamil Nadu 600020',
    city: 'Chennai',
    locality: 'Adyar',
    latitude: 13.0100,
    longitude: 80.2600,
  },
  {
    name: 'Shirdi Sai Baba Temple',
    deity: 'Sai Baba',
    address: 'Venkatesa Agraharam, Mylapore, Chennai, Tamil Nadu 600004',
    city: 'Chennai',
    locality: 'Mylapore',
    latitude: 13.0339,
    longitude: 80.2628,
  },
  {
    name: 'Thirumalai Thirupathi Devasthanam Temple',
    deity: 'Venkateswara',
    address: 'Venkata Narayana Road, T.Nagar, Chennai, Tamil Nadu 600017',
    city: 'Chennai',
    locality: 'T. Nagar',
    latitude: 13.0400,
    longitude: 80.2400,
  },
  {
    name: 'Thiruneermalai Vishnu Temple',
    deity: 'Vishnu',
    address: 'Thiruneermalai, Chennai, Tamil Nadu',
    city: 'Chennai',
    locality: 'Thiruneermalai',
    latitude: 12.9500,
    longitude: 80.1000,
  },
  {
    name: 'Vedagiriswarar Temple',
    deity: 'Shiva',
    address: 'Thirukkalukundram, Chennai, Tamil Nadu',
    city: 'Chennai',
    locality: 'Thirukkalukundram',
    latitude: 12.6000,
    longitude: 80.0500,
  },
  {
    name: 'Mangadu Kamakshiamman Temple',
    deity: 'Kamakshi Amman',
    address: 'Mangadu, Chennai, Tamil Nadu',
    city: 'Chennai',
    locality: 'Mangadu',
    latitude: 13.0800,
    longitude: 80.1000,
  },
  {
    name: 'Adeeswar Temple (Vada Sabari)',
    deity: 'Ayyappan',
    address: 'Raja Annamalaipuram, Chennai, Tamil Nadu 600028',
    city: 'Chennai',
    locality: 'Raja Annamalaipuram',
    latitude: 13.0200,
    longitude: 80.2700,
  },
]
